quarkus:
  default-locale: en-GB
  locales: en-GB,en-US,fr-FR

  kubernetes-client:
    devservices:
      enabled: false

  info:
    os:
      enabled: false

  management:
    enabled: true
    port: 8081
  oidc:
    client-id: provoly-hypervisor

  flyway:
    default-schema: provoly_hypervisor
    migrate-at-start: true
    validate-on-migrate: true
  hibernate-orm:
    physical-naming-strategy: io.hypersistence.utils.hibernate.naming.CamelCaseToSnakeCaseNamingStrategy
    database:
      default-schema: provoly_hypervisor


mp:
  messaging:
    outgoing:
      equipment:
        connector: smallrye-kafka
        topic: equipment


"%dev":
  quarkus:
    smallrye-openapi:
      path: /openapi.yaml

    flyway:
      repair-at-start: true

    log:
      category:
        "org.hibernate":
          level: INFO
        "io.quarkus.oidc":
          level: INFO
        "com.provoly":
          level: INFO
        "org.jboss.resteasy.reactive.server":
          level: DEBUG
        "WebApplicationException":
          level: DEBUG
        min-level: TRACE
      console:
        format: "%d{HH:mm:ss} %-5p traceId=%X{traceId} parentId=%X{parentId} spanId=%X{spanId} [%c{2.}] (%t) %s%e%n"

    hibernate-orm:
      log:
        sql: false
        bind-parameters: false

    keycloak:
      devservices:
        realm-name: provoly
        realm-path: src/main/keycloak/realm.json
        port: 9080

    datasource:
      devservices:
        port: 5433
        init-script-path: db/init.sql

    kafka:
      devservices:
        image-name: docker.io/redpandadata/redpanda:v24.1.2
        enabled: true
        port: 9093

    oidc:
      token:
        # Auth Server clock can be xx seconds ahead of resource server
        lifespan-grace: 120
      roles:
        role-claim-path: "realm_access/roles"

    http:
      access-log:
        enabled: true
      port: 8087

    management:
      enabled: false # Mainly to avoid conflicts with other quarkus process

    otel:
      sdk:
        disabled: true
      exporter:
        resource-attributes: env=tracingTest
        otlp:
          enabled: false
          endpoint: http://localhost:4317

  coswin:
    scheme: http
    host: coswin.host.fr
    port: 8080
    username: username
    password: password
    dataSource: datasource
    cwUser: cwUser

"%prod":
  quarkus:
    kubernetes-config:
      enabled: true
      config-maps: provoly-hypervisor-backend