### Mailer ###
quarkus.mailer.from=administrador@sysgarantia.com
quarkus.mailer.host=sandbox.smtp.mailtrap.io
quarkus.mailer.port=587
quarkus.mailer.username=username
quarkus.mailer.password=password
quarkus.mailer.start-tls=REQUIRED
# In dev mode, prevent from using the mock SMTP server
quarkus.mailer.mock=true

#in-hello-channel.mail-send.timeout.seconds=30

### Kafka ###
mp.messaging.incoming.in-fail-hello-channel.topic=fail-hello-topic

mp.messaging.incoming.in-hello-channel.topic=hello-topic
mp.messaging.outgoing.out-hello-channel.topic=hello-topic

mp.messaging.incoming.in-hello-channel.dead-letter-queue.topic=fail-hello-topic
mp.messaging.outgoing.out-hello-channel.dead-letter-queue.topic=fail-hello-topic

mp.messaging.incoming.in-hello-channel.failure-strategy=dead-letter-queue
mp.messaging.outgoing.out-hello-channel.failure-strategy=dead-letter-queue

mp.messaging.incoming.in-hello-channel.connector=smallrye-kafka
mp.messaging.outgoing.out-hello-channel.connector=smallrye-kafka

mp.messaging.connector.smallrye-kafka.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.connector.smallrye-kafka.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.connector.smallrye-kafka.retry-attempts=3
mp.messaging.connector.smallrye-kafka.bootstrap.servers=localhost:9092
