quarkus.log.category.dev.ai4j.openai4j.level=DEBUG
llm.url=localhost:11434
quarkus.native.resources.includes=camel/route-main.camel.yaml,camel/route-tool-guide.camel.yaml,camel/route-tool-weather.camel.yaml,index.html,style.css
camel.main.routes-include-pattern=camel/route-main.camel.yaml,camel/route-tool-guide.camel.yaml,camel/route-tool-weather.camel.yaml
quarkus.langchain4j.openai.api-key=EMPTY
%dev.quarkus.http.host=0.0.0.0
