quarkus.http.port=12002

quarkus.swagger-ui.theme=original
quarkus.swagger-ui.always-include=true

quarkus.smallrye-openapi.store-schema-directory=build/openapi
quarkus.smallrye-openapi.info-title=Student API
%dev.quarkus.smallrye-openapi.info-title=Student API (development)
%test.quarkus.smallrye-openapi.info-title=Student API (test)
quarkus.smallrye-openapi.info-version=${quarkus.application.version}
quarkus.smallrye-openapi.info-description=There is a Student API backend
quarkus.smallrye-openapi.info-terms-of-service=Your terms here
quarkus.smallrye-openapi.info-contact-email=techsupport@example.com
quarkus.smallrye-openapi.info-contact-name=Example API Support
quarkus.smallrye-openapi.info-contact-url=http://exampleurl.com/contact
quarkus.smallrye-openapi.info-license-name=Apache 2.0
quarkus.smallrye-openapi.info-license-url=https://www.apache.org/licenses/LICENSE-2.0.html

#quarkus.container-image.build=true
#quarkus.container-image.push=true
quarkus.container-image.registry=ghcr.io
quarkus.container-image.group=fenrur/microservice-student
quarkus.jib.platforms=linux/arm64,linux/amd64
quarkus.container-image.builder=jib
quarkus.jib.use-current-timestamp=false
quarkus.jib.use-current-timestamp-file-modification=false

quarkus.http.cors=true
quarkus.http.cors.origins=/.*/

quarkus.mongodb.database=student
quarkus.mongodb.devservices.port=32771

quarkus.rest-client."fr.livio.SchoolService".url=stork://school

consul.host=localhost
consul.port=8500
consul.name=${quarkus.application.name}

quarkus.stork.school.service-discovery.type=consul